# Docker Compose
:source-highlighter: pygments
:pygments-style: manni
:icons: font
:figure-caption!:

* https://github.com/bitnami/bitnami-docker-rails[bitnami/bitnami-docker-rails].
* https://zwischenzugs.com/2018/04/23/unprivileged-docker-builds-a-proof-of-concept/[Unprivileged Docker Builds – A Proof of Concept].

## My Rails with PostgreSQL

How to generate a skeletal Rails installation without Ruby installed?

[source,sh]
----
cd rails-pg
# docker build --tag rails-pg .
docker build --no-cache --tag rails-pg .
docker images
----

https://docs.docker.com/engine/reference/builder/[Dockerfile reference].

[source,sh]
.Dockerfile
----
FROM ruby:2.5.0
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN gem install rails --version '~> 5.2.0'
RUN rails new myapp --database=postgresql --skip-action-cable --skip-coffee --skip-test --skip-bundle

WORKDIR /myapp

COPY database.yml config

RUN bin/bundle install

COPY Dockerfile .
COPY docker-compose.yml .
COPY .dockerignore .
----

https://docs.docker.com/compose/compose-file/[Compose file version 3 reference].

[source,sh]
----
version: '3.6'

services:

  db:
    image: postgres:10.3
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: bin/rails server --port 3000 --binding '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
----


## My Rails with PostgreSQL App

[source,sh]
----
cd ..
docker images
docker run rails-pg
docker ps -a
# brave_lovelace -- container name of the running my-rails-app

rm -rf my-rails-app
docker cp brave_lovelace:/myapp/ my-rails-app
docker container rm brave_lovelace

cd my-rails-app

# TODO: rename Dockerfile -> Dockerfile-rails-pg
# TODO: add new Dockerfile
# TODO: add _.dockerignore_ file
----


## Docker Compose and Rails – Quickstart

* https://docs.docker.com/compose/rails/[Quickstart: Compose and Rails].

TODO: change Dockerfile
[source,sh]
----
FROM rails-pg:latest

WORKDIR /myapp
COPY . .
# TODO: add bin/bundle check
RUN bin/bundle install
----

* https://docs.docker.com/compose/compose-file/[Compose file version 3 reference].
* https://docs.docker.com/compose/reference/[Compose command-line reference].
* https://docs.docker.com/compose/rails/[Quickstart: Compose and Rails]


### View the Rails welcome page!

[source,sh]
----
docker-compose run web bin/rails db:create

docker-compose up --build
# localhost:3000 – Yay! You’re on Rails!
----

### Start & Restart, Stop and Rebuild the application

[source,sh]
----
docker-compose up
docker compose stop
docker compose down
----


### Run and Exec commands

[source,sh]
----
docker-compose run web bin/rails db:migrate

# or
docker-compose up
docker-compose exec web bin/rails db:migrate
----


### Add pry-rails gem

Add _pry-rails_ gem to development group.
[source,ruby]
.Gemfile
----
group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry-rails'
end
----

Now, update _Gemfile.lock_ and rebuild web service.
[source,sh]
----
docker-compose up --build
docker-compose exec web bin/rails console
# Yay! You’re on Pry console
----


### Generate scaffold

[source,sh]
----
docker-compose exec web bin/rails generate scaffold post title:string body:text published:boolean
docker-compose exec web bin/rails db:migrate

docker-compose exec web bin/rails console
# pry(main)> show-<press TAB>
# pry(main)> show-models
# localhost:3000/posts
----


### Routing

Set the application Home Page:
[source,ruby]
.Update routing in config/routes.rb
----
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
end
----


### Expose another port

Update web service – expose port 80 on the host.
[source,yml]
.docker-compose.yml
----
ports:
  - "80:3000"
----

Recreate web service.
[source,sh]
----
docker-compose down # 3000
docker-compose up   #   80
----




## Images with ENTRYPOINT & CMD

[source,sh]
.Dockerfile
----
# sample Dockerfile with entry point
----

[source,bash]
----
docker run --rm ubuntu-man-git
# nothing appears to happen …

docker run --name command-git --entrypoint git ubuntu-man-git
docker ps -a
docker commit -a "@wbzyl" -m "Set CMD git" command-git ubuntu-git

docker rm -vf command-git

docker run --name command-git ubuntu-git version
#=> git version 2.7.4
----


## Echo server

MacOS, install *netcat*:
[source,sh]
----
brew install netcat
----


### Server

[source,sh]
----
docker container rm $(docker container ls -a -q)
----
