version: '3.6'

services:

  db:
    image: postgres:10.3
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: bin/rails server --port 3000 --binding '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
