version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bin/rails server --port 3000 --binding '0.0.0.0'
    # volumes:
    #   - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
